.TH relay-ctrl-age 8
.SH NAME
relay-ctrl-age \- age the list of addresses allowed by relay-ctrl-allow
.SH SYNOPSIS
.B relay-ctrl-age
.SH DESCRIPTION
.B relay-ctrl-age
examines the dates on the all the relay client IP files in the
directory specified by
.I $RELAY_CTRL_DIR
and removes any that have not been created or modified in the last
.I $RELAY_CTRL_EXPIRY
seconds (defaults to 900 seconds or 15 minutes).
.SH "SEE ALSO"
relay-ctrl-allow(8),
relay-ctrl-check(8)
