.TH relay-ctrl-allow 8
.SH NAME
relay-ctrl-allow \- selectively enable smtp relaying
.SH SYNOPSIS
.B relay-ctrl-allow
.I command
[
.I arguments ...
]
.SH DESCRIPTION
.B relay-ctrl-allow
adds a record of the remote host's address to a spool directory to
enable the remote host to subsequently use this host to relay email.
After recording the address, it executes
.B relay-ctrl-age
in the background to add the new address to the table used by
.B tcpserver
to control relaying.
Before executing the given command,
.B relay-ctrl-allow
drops all setuid priviledges.
.SH OPTIONS
.TP
.B command
This argument is executed after the IP address has been added to the
spool of addresses.
.SH "RETURN VALUES"
Returns 111 (temporary failure) if any operation fails; 0 otherwise.
.SH ENVIRONMENT
.TP
.B TCPREMOTEIP
.B relay-ctrl-allow
expects that this environment variable is set to the numerical IP
address of the remote host.
.SH FILES
.TP
.B /var/spool/relay-ctrl
The directory into which the address is placed.
.SH "SEE ALSO"
relay-ctrl-age(8),
qmail-pop3d(8),
qmail-popup(8),
tcpserver(1),
tcp-environ(5)
.SH WARNINGS
.B relay-ctrl-allow
will normally need to be installed setuid root, as it will be executed
without permissions to modify either the spool directory or the SMTP
rules CDB used by
.B tcpserver .
.P
.B relay-ctrl-allow
requires that file descriptors 0 and 1 (standard in and standard out)
are opened to a socket, which will be the case if it is invoked from
.B tcpserver .
